# Generated by Django 3.1 on 2020-08-26 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.patternview'),
        ),
        migrations.AddField(
            model_name='patternview',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.pattern'),
        ),
        migrations.AddField(
            model_name='patternview',
            name='pattern_type',
            field=models.ManyToManyField(to='patterns.PatternType'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.patterncompany'),
        ),
    ]
