# Generated by Django 3.1 on 2020-08-26 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0002_auto_20200826_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['owner', 'start_date']},
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
