# Generated by Django 3.1 on 2020-08-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0003_auto_20200826_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['owner']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
